"""Workspace scaffolding for different runtimes.

The agent can generate code from scratch, but providing a minimal project scaffold
reduces friction (e.g. Node projects need a package.json and an obvious test
command).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

from src.ui.logger import get_logger


SCAFFOLD_MARKER = ".agent_scaffold.json"


class ProjectScaffolder:
    def __init__(self):
        self.logger = get_logger("project_scaffolder")

    def ensure_scaffold(
        self,
        *,
        workspace: Path,
        language: str,
        project_type: str = "general",
    ) -> Dict[str, Any]:
        """Ensure a workspace has a minimal scaffold.

        Returns a dict with information about scaffold actions.
        """

        workspace.mkdir(parents=True, exist_ok=True)

        marker_path = workspace / SCAFFOLD_MARKER
        if marker_path.exists():
            return {"scaffolded": False, "reason": "already_scaffolded"}

        existing_files = [
            p
            for p in workspace.rglob("*")
            if p.is_file() and p.name != SCAFFOLD_MARKER
        ]
        if existing_files:
            return {"scaffolded": False, "reason": "workspace_not_empty"}

        language_norm = (language or "python").lower()
        if language_norm in {"node", "javascript", "js"}:
            self._scaffold_node(workspace)
        else:
            self._scaffold_python(workspace)

        marker_path.write_text(
            json.dumps(
                {
                    "language": language_norm,
                    "project_type": project_type,
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

        return {"scaffolded": True, "language": language_norm, "project_type": project_type}

    def _scaffold_python(self, workspace: Path):
        (workspace / "README.md").write_text(
            "# Agent Workspace (Python)\n\nGenerated by the autonomous coding agent.\n",
            encoding="utf-8",
        )

    def _scaffold_node(self, workspace: Path):
        (workspace / "README.md").write_text(
            "# Agent Workspace (Node.js)\n\nGenerated by the autonomous coding agent.\n",
            encoding="utf-8",
        )

        package_json = {
            "name": "agent-workspace",
            "version": "0.0.0",
            "private": True,
            "type": "commonjs",
            "scripts": {"test": "node --test"},
        }
        (workspace / "package.json").write_text(
            json.dumps(package_json, indent=2) + "\n",
            encoding="utf-8",
        )

        (workspace / "src").mkdir(parents=True, exist_ok=True)
        (workspace / "src" / "index.js").write_text(
            "'use strict';\n\nmodule.exports = {};\n",
            encoding="utf-8",
        )

        (workspace / "test").mkdir(parents=True, exist_ok=True)
        (workspace / "test" / "smoke.test.js").write_text(
            "const test = require('node:test');\nconst assert = require('node:assert/strict');\n\nconst lib = require('../src/index');\n\ntest('smoke: module loads', () => {\n  assert.equal(typeof lib, 'object');\n});\n",
            encoding="utf-8",
        )
